### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by xuwei-k** [atware/sharedocs#7]
![2017-01-17 19 41 51](https://cloud.githubusercontent.com/assets/389787/22017274/043f09ec-dced-11e6-8493-a1fe43a49f71.png)

<hr />

![2017-01-17 19 40 26](https://cloud.githubusercontent.com/assets/389787/22017231/da30b90c-dcec-11e6-8eb5-1e4c1083ddfe.png)

**Comment by roundrop** [comment]
It's an assumption of the tool used within an internal organization, so I did not validate strictly.
However, there is no reason to allow the script tag, so we've fixed.
Thanks
