### ISSUE TITLE
can't build with Scala 2.12

### ISSUE THREAD

**Issue by xuwei-k** [atware/sharedocs#9]
README says `Scala 2.11 or 2.12` but 
`"com.github.t3hnar"       % "scala-bcrypt_2.12"         % "2.6"`
does not exists.

- https://repo1.maven.org/maven2/com/github/t3hnar/scala-bcrypt_2.12/
- https://github.com/atware/sharedocs/blob/58ce989ca4ac8e3/build.sbt#L49

**Comment by roundrop** [comment]
fixed by #4
